// 아니마룬 — 오프라인 실행용 서비스 워커
// 파일을 새 버전으로 올릴 때 아래 CACHE 이름의 숫자를 올리면 예전 캐시가 정리돼요. index.html 의 APP_BUILD 도 같은 숫자로 (업데이트 버튼이 이 숫자를 비교)
const CACHE = 'animarune-v279';
const APP_VERSION = '2.81'; // (v276) 게임에 보이는 버전 — index.html의 APP_VERSION과 같게 (CACHE 숫자는 내부 번호라 1씩만 올림)
const FILES = ['./', './index.html', './manifest.webmanifest', './icon-180.png', './icon-192.png', './icon-512.png', './assets/fonts/jua-sub.woff2', './assets/home_stage.webp', './assets/home_expedition.webp', './assets/home_raid.webp', './assets/battle_snow.webp', './assets/battle_raid_frostTyrant.webp', './assets/battle_raid_infernoDrake.webp', './assets/battle_raid_abyssEye.webp', './assets/battle_raid_eldertree.webp', './assets/battle_raid_dawnJudge.webp', './assets/battle_plains.webp', './assets/battle_arena.webp', './assets/battle_volcano.webp', './assets/battle_forest.webp', './assets/battle_desert.webp', './assets/battle_cave.webp',
  './assets/boss/frostGiant.webp', './assets/boss/lavaLord.webp', './assets/boss/ancientTree.webp', './assets/boss/ruinGuardian.webp', './assets/boss/abyssCrystal.webp', './assets/boss/frostTyrant.webp', './assets/boss/infernoDrake.webp', './assets/boss/abyssEye.webp', './assets/boss/eldertree.webp', './assets/boss/dawnJudge.webp',
  './assets/ui/frame_common.webp', './assets/ui/frame_epic.webp', './assets/ui/frame_legendary.webp', './assets/ui/frame_mythic.webp', './assets/ui/frame_rare.webp', './assets/ui/ic_achieve.webp', './assets/ui/ic_atk.webp', './assets/ui/ic_lock.webp', './assets/ui/ic_shield.webp', './assets/ui/ic_gift.webp', './assets/ui/ic_check.webp', './assets/ui/ic_crown.webp', './assets/ui/ic_medal.webp', './assets/ui/ic_star.webp', './assets/ui/ic_power.webp', './assets/ui/ic_trophy.webp', './assets/ui/ic_skull.webp', './assets/ui/ic_party.webp', './assets/ui/ic_shard.webp', './assets/ui/ic_enemy.webp', './assets/ui/ic_special.webp', './assets/ui/ic_groggy.webp', './assets/ui/ic_pass.webp', './assets/ui/ic_dex.webp', './assets/ui/ic_target.webp', './assets/ui/ic_recycle.webp', './assets/ui/ic_guard.webp', './assets/ui/ic_fuse.webp', './assets/ui/ic_tk_summon.webp', './assets/ui/ic_tk_rare.webp', './assets/ui/ic_tk_legendary.webp', './assets/ui/ic_tk_equip.webp', './assets/ui/ic_tk_exp.webp', './assets/ui/ic_awaken.webp', './assets/ui/ic_tk_pick_rare.webp', './assets/ui/ic_tk_pick_epic.webp', './assets/ui/ic_tk_pick_legendary.webp', './assets/ui/ic_tk_pick_mythic.webp', './assets/ui/ic_duel.webp', './assets/ui/ic_el_dark.webp', './assets/ui/ic_el_fire.webp', './assets/ui/ic_el_light.webp', './assets/ui/ic_el_water.webp', './assets/ui/ic_el_wood.webp', './assets/ui/ic_essence.webp', './assets/ui/ic_expedition.webp', './assets/ui/ic_explore.webp', './assets/ui/ic_friends.webp', './assets/ui/ic_guide.webp', './assets/ui/ic_hearth.webp', './assets/ui/ic_menu.webp', './assets/ui/ic_quest.webp', './assets/ui/ic_raid.webp', './assets/ui/ic_runestone.webp', './assets/ui/ic_settings.webp', './assets/ui/ic_spirits.webp', './assets/ui/ic_stone.webp', './assets/ui/ic_summon.webp', './assets/ui/ic_ticket.webp', './assets/ui/ic_tower.webp',
  './assets/spirits/dark_common_a.webp', './assets/spirits/dark_common_b.webp', './assets/spirits/dark_epic_a.webp', './assets/spirits/dark_epic_b.webp', './assets/spirits/dark_legendary_a.webp', './assets/spirits/dark_legendary_b.webp', './assets/spirits/dark_mythic_a.webp', './assets/spirits/dark_mythic_b.webp', './assets/spirits/dark_rare_a.webp', './assets/spirits/dark_rare_b.webp', './assets/spirits/fire_common_a.webp', './assets/spirits/fire_common_b.webp', './assets/spirits/fire_epic_a.webp', './assets/spirits/fire_epic_b.webp', './assets/spirits/fire_legendary_a.webp', './assets/spirits/fire_legendary_b.webp', './assets/spirits/fire_mythic_a.webp', './assets/spirits/fire_mythic_b.webp', './assets/spirits/fire_rare_a.webp', './assets/spirits/fire_rare_b.webp', './assets/spirits/light_common_a.webp', './assets/spirits/light_common_b.webp', './assets/spirits/light_epic_a.webp', './assets/spirits/light_epic_b.webp', './assets/spirits/light_legendary_a.webp', './assets/spirits/light_legendary_b.webp', './assets/spirits/light_mythic_a.webp', './assets/spirits/light_mythic_b.webp', './assets/spirits/light_rare_a.webp', './assets/spirits/light_rare_b.webp', './assets/spirits/water_common_a.webp', './assets/spirits/water_common_b.webp', './assets/spirits/water_epic_a.webp', './assets/spirits/water_epic_b.webp', './assets/spirits/water_legendary_a.webp', './assets/spirits/water_legendary_b.webp', './assets/spirits/water_mythic_a.webp', './assets/spirits/water_mythic_b.webp', './assets/spirits/water_rare_a.webp', './assets/spirits/water_rare_b.webp', './assets/spirits/wood_common_a.webp', './assets/spirits/wood_common_b.webp', './assets/spirits/wood_epic_a.webp', './assets/spirits/wood_epic_b.webp', './assets/spirits/wood_legendary_a.webp', './assets/spirits/wood_legendary_b.webp', './assets/spirits/wood_mythic_a.webp', './assets/spirits/wood_mythic_b.webp', './assets/spirits/wood_rare_a.webp', './assets/spirits/wood_rare_b.webp', './assets/ui/eq_armor_dark.webp', './assets/ui/eq_armor_fire.webp', './assets/ui/eq_armor_light.webp', './assets/ui/eq_armor_water.webp', './assets/ui/eq_armor_wood.webp', './assets/ui/eq_weapon_dark.webp', './assets/ui/eq_weapon_fire.webp', './assets/ui/eq_weapon_light.webp', './assets/ui/eq_weapon_water.webp', './assets/ui/eq_weapon_wood.webp', './assets/ui/rune_abyss.webp', './assets/ui/rune_atk.webp', './assets/ui/rune_crit.webp', './assets/ui/rune_dr.webp', './assets/ui/rune_elder.webp', './assets/ui/rune_frost.webp', './assets/ui/rune_hp.webp', './assets/ui/rune_inferno.webp', './assets/ui/rune_judge.webp', './assets/ui/rune_life.webp', './assets/ui/rune_spd.webp'];
self.addEventListener('install', e=>{
  e.waitUntil(caches.open(CACHE).then(c=>Promise.all(FILES.map(f=>c.add(f).catch(()=>{})))).then(()=>self.skipWaiting()));
});
self.addEventListener('activate', e=>{
  e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));
});
// (v227) 그림·소리 등 assets/ 는 캐시 우선(캐시 이름을 올릴 때마다 새로 받음) — 모바일에서 한꺼번에 요청하다 실패해도 캐시로 바로 뜸
// 페이지(HTML)·코드는 네트워크 우선. 실패했을 때 index.html 로 대신하는 건 화면 이동 요청일 때만(예전엔 그림 요청에도 HTML을 돌려줘서 그림이 깨져 보였음)
self.addEventListener('fetch', e=>{
  const req = e.request;
  if(req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  const save = res=>{ if(res && res.ok){ const copy = res.clone(); caches.open(CACHE).then(c=>c.put(req, copy)); } return res; };
  if(new URL(req.url).pathname.indexOf('/assets/') >= 0){
    e.respondWith(caches.match(req).then(r=> r || fetch(req).then(save)));
    return;
  }
  // (v263) 화면 이동(페이지) 요청은 브라우저 HTTP 캐시를 거치지 않고 서버에 확인(no-cache) — 옛 index.html 이 몇 분씩 남던 문제
  // (v266) 주소가 넘어간(리다이렉트) 응답을 페이지로 그대로 주면 Safari 는 'WebKit 내부 오류', 크롬은 ERR_FAILED 로 막힘 → 깨끗한 응답으로 다시 만들어서 줌
  const unredirect = res=> (res && res.redirected) ? res.blob().then(body=> new Response(body, { status:res.status, statusText:res.statusText, headers:res.headers })) : res;
  const net = req.mode==='navigate' ? fetch(req.url, {cache:'no-cache', credentials:'same-origin'}).then(unredirect) : fetch(req);
  e.respondWith(
    net.then(save).catch(()=> caches.match(req).then(r=> r || (req.mode==='navigate' ? caches.match('./index.html') : Response.error())))
  );
});
