// 아니마룬 — 오프라인 실행용 서비스 워커
// 파일을 새 버전으로 올릴 때 아래 CACHE 이름의 숫자를 올리면 예전 캐시가 정리돼요.
const CACHE = 'animarune-v222';
const FILES = ['./', './index.html', './manifest.webmanifest', './icon-180.png', './icon-192.png', './icon-512.png', './assets/fonts/jua-sub.woff2', './assets/home_stage.webp', './assets/home_expedition.webp', './assets/home_raid.webp', './assets/battle_snow.webp', './assets/battle_raid_frostTyrant.webp', './assets/battle_raid_infernoDrake.webp', './assets/battle_raid_abyssEye.webp', './assets/battle_raid_eldertree.webp', './assets/battle_raid_dawnJudge.webp', './assets/battle_plains.webp', './assets/battle_arena.webp', './assets/battle_volcano.webp', './assets/battle_forest.webp', './assets/battle_desert.webp', './assets/battle_cave.webp',
  './assets/boss/frostGiant.webp', './assets/boss/lavaLord.webp', './assets/boss/ancientTree.webp', './assets/boss/ruinGuardian.webp', './assets/boss/abyssCrystal.webp', './assets/boss/frostTyrant.webp', './assets/boss/infernoDrake.webp', './assets/boss/abyssEye.webp', './assets/boss/eldertree.webp', './assets/boss/dawnJudge.webp',
  './assets/ui/frame_common.webp', './assets/ui/frame_epic.webp', './assets/ui/frame_legendary.webp', './assets/ui/frame_mythic.webp', './assets/ui/frame_rare.webp', './assets/ui/ic_achieve.webp', './assets/ui/ic_duel.webp', './assets/ui/ic_el_dark.webp', './assets/ui/ic_el_fire.webp', './assets/ui/ic_el_light.webp', './assets/ui/ic_el_water.webp', './assets/ui/ic_el_wood.webp', './assets/ui/ic_essence.webp', './assets/ui/ic_expedition.webp', './assets/ui/ic_explore.webp', './assets/ui/ic_friends.webp', './assets/ui/ic_guide.webp', './assets/ui/ic_hearth.webp', './assets/ui/ic_menu.webp', './assets/ui/ic_quest.webp', './assets/ui/ic_raid.webp', './assets/ui/ic_runestone.webp', './assets/ui/ic_settings.webp', './assets/ui/ic_spirits.webp', './assets/ui/ic_stone.webp', './assets/ui/ic_summon.webp', './assets/ui/ic_ticket.webp', './assets/ui/ic_tower.webp',
  './assets/spirits/dark_common_a.webp', './assets/spirits/dark_common_b.webp', './assets/spirits/dark_epic_a.webp', './assets/spirits/dark_epic_b.webp', './assets/spirits/dark_legendary_a.webp', './assets/spirits/dark_legendary_b.webp', './assets/spirits/dark_mythic_a.webp', './assets/spirits/dark_mythic_b.webp', './assets/spirits/dark_rare_a.webp', './assets/spirits/dark_rare_b.webp', './assets/spirits/fire_common_a.webp', './assets/spirits/fire_common_b.webp', './assets/spirits/fire_epic_a.webp', './assets/spirits/fire_epic_b.webp', './assets/spirits/fire_legendary_a.webp', './assets/spirits/fire_legendary_b.webp', './assets/spirits/fire_mythic_a.webp', './assets/spirits/fire_mythic_b.webp', './assets/spirits/fire_rare_a.webp', './assets/spirits/fire_rare_b.webp', './assets/spirits/light_common_a.webp', './assets/spirits/light_common_b.webp', './assets/spirits/light_epic_a.webp', './assets/spirits/light_epic_b.webp', './assets/spirits/light_legendary_a.webp', './assets/spirits/light_legendary_b.webp', './assets/spirits/light_mythic_a.webp', './assets/spirits/light_mythic_b.webp', './assets/spirits/light_rare_a.webp', './assets/spirits/light_rare_b.webp', './assets/spirits/water_common_a.webp', './assets/spirits/water_common_b.webp', './assets/spirits/water_epic_a.webp', './assets/spirits/water_epic_b.webp', './assets/spirits/water_legendary_a.webp', './assets/spirits/water_legendary_b.webp', './assets/spirits/water_mythic_a.webp', './assets/spirits/water_mythic_b.webp', './assets/spirits/water_rare_a.webp', './assets/spirits/water_rare_b.webp', './assets/spirits/wood_common_a.webp', './assets/spirits/wood_common_b.webp', './assets/spirits/wood_epic_a.webp', './assets/spirits/wood_epic_b.webp', './assets/spirits/wood_legendary_a.webp', './assets/spirits/wood_legendary_b.webp', './assets/spirits/wood_mythic_a.webp', './assets/spirits/wood_mythic_b.webp', './assets/spirits/wood_rare_a.webp', './assets/spirits/wood_rare_b.webp', './assets/ui/eq_armor_dark.webp', './assets/ui/eq_armor_fire.webp', './assets/ui/eq_armor_light.webp', './assets/ui/eq_armor_water.webp', './assets/ui/eq_armor_wood.webp', './assets/ui/eq_weapon_dark.webp', './assets/ui/eq_weapon_fire.webp', './assets/ui/eq_weapon_light.webp', './assets/ui/eq_weapon_water.webp', './assets/ui/eq_weapon_wood.webp', './assets/ui/rune_abyss.webp', './assets/ui/rune_atk.webp', './assets/ui/rune_crit.webp', './assets/ui/rune_dr.webp', './assets/ui/rune_elder.webp', './assets/ui/rune_frost.webp', './assets/ui/rune_hp.webp', './assets/ui/rune_inferno.webp', './assets/ui/rune_judge.webp', './assets/ui/rune_life.webp', './assets/ui/rune_spd.webp'];
self.addEventListener('install', e=>{
  e.waitUntil(caches.open(CACHE).then(c=>Promise.all(FILES.map(f=>c.add(f).catch(()=>{})))).then(()=>self.skipWaiting()));
});
self.addEventListener('activate', e=>{
  e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));
});
// 네트워크 우선(온라인이면 항상 최신), 실패하면 캐시
self.addEventListener('fetch', e=>{
  const req = e.request;
  if(req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    fetch(req).then(res=>{
      if(res && res.ok){ const copy = res.clone(); caches.open(CACHE).then(c=>c.put(req, copy)); }
      return res;
    }).catch(()=> caches.match(req).then(r=> r || caches.match('./index.html')))
  );
});
